### ISSUE TITLE
Nuevos requisitos a cumplir

### ISSUE THREAD

**Issue by ivanortegaalba** [CongressWebDevelopers/web-congreso#38]
## REQUISITOS DEL CLIENTE

Hemos recibido las siguientes instrucciones del cliente que hay que implementar:
- [x] Quiero que cuando el visitante esté mirando un trabajo concreto del programa, le aparezca de forma contextual el resto de trabajos de la misma sesión. #41 
- [x] Quiero que el formulario de contacto me remita un e- mail con el mensaje, y que llegue otra copia a la persona que lo ha rellenado. El e-mail debe tener como asunto “[Mensaje de Web] Asunto”. #42
- [x] Necesito poder cambiar las fotos de las actividades y su texto descriptivo con facilidad, sin necesidad de tocar el código. #43
## REQUISITOS DE IMPLEMENTACIÓN

Los requisitos del cliente se implementarán con las siguientes restricciones/sugerencias:
- [x] Debe hacerse con un único archivo contexmenu.php que mostrará las opciones
  según lo que se esté visualizando en el content. #41 
- [x] La función mail() de PHP debería ser más que suficiente, pero la red de la UGR bloquea el puerto de envío de e-mails con esa función, por lo que habrá que usar un SMTP externo (p.ej. Gmail). #42
- [x] Se debe usar un archivo de texto donde se indiquen las imágenes para cada actividad y su texto descriptivo. Este archivo será el que el cliente modificará, y de él se leerán las rutas para mostrar las fotografías y la información. #43

**Comment by ivanortegaalba** [comment]
@jota-ele256 Todo terminado y listo para entrega.
