### ISSUE TITLE
Requisitos a cumplir para el siguiente plazo

### ISSUE THREAD

**Issue by ivanortegaalba** [CongressWebDevelopers/web-congreso#52]
- [x] Las cuotas y las actividades opcionales se almacenarán en la base de datos #53
- [ ] Los hoteles estarán accesibles a través de un servicio externo, desarrollado en la asignatura DGP. #54
- [x] Los usuarios se podrán registrar en el congreso #55
- [ ] Se incluirán acciones para recordar el usuario y la contraseña #56
- [x] Cualquier usuario identificado podrá inscribirse en el congreso #57
- [ ] Habrá un usuario especial, con rol de administrador, que podrá ver qué personas están inscritas en cada momento #58
- [ ] El usuario administrador podrá modificar las cuotas y actividades del congreso a través de la propia página web, sin necesidad de usar el archivo de texto de la práctica anterior. #59

**Comment by ivanortegaalba** [comment]
@jota-ele256 para este viernes hacemos la base de datos de actividades y cuotas volcando en una clase en PHP(controlador).

**Comment by joseluisfdezbueno** [comment]
@ivanortegaalba  perfecto. Yo tengo mañana por la tarde examen, así que me pondré por la noche, cuando llegue a casa vaya. Si quieres, haz tú mientras la estructura base y yo lo termino. O lo repartimos como mejor tú veas.

**Comment by ivanortegaalba** [comment]
Haré el controlador de cuota y usuario, y tu lo usas como base para actividad :+1:

**Comment by joseluisfdezbueno** [comment]
@ivanortegaalba he creado las tablas de actividades y cuotas a través de phpmyadmin en localhost, por tanto solo se genera el contenido en php cuando lo abro desde mi pc...cómo se puede hacer para abrirlo desde cualquier lado?

**Comment by ivanortegaalba** [comment]
@jota-ele256 voy a hacer en mi web un post de como hacerlo y te lo paso, así mato ya dos pajaros de un tiro :)

**Comment by ivanortegaalba** [comment]
@jota-ele256 aquí tienes http://www.ivanprograma.com/?p=148

**Comment by ivanortegaalba** [comment]
¿Tienes twitter?

**Comment by joseluisfdezbueno** [comment]
@ivanortegaalba gracias, muy guapa tu web ;) No tengo twitter, pero al final caeré supongo...xD

**Comment by joseluisfdezbueno** [comment]
He subido a mi rama, lo de las actividades y cuotas. He modificado un poco el ORM. Pero me pasa una cosa super rara...en el index o donde sea, si hago include con el .php donde esta la clase ORM, no me funciona, lo haga como lo haga.....He tenido que escribir al principio del index la clase tal cual, para poder avanzar....prueba tu a comentarla y a descomentar la de "include_once 'ORM.php' A ver si te funciona.....ah, y las tablas de sql las he metido en la carpeta db

**Comment by ivanortegaalba** [comment]
Has hecho merge? Es que he hecho muchísimos cambios.
Ivan Ortega Alba

4º Grado en Ingeniería Informática
Especialidad en Tecnologías de la Comunicación
Escuela Técnica Superior de Ingeniería Informática y Telecomunicación.
Universidad de Granada

**Comment by joseluisfdezbueno** [comment]
No, no he hecho merge. Yo he trabajado sobre el último contenido que subiste a master hace 3 días

**Comment by ivanortegaalba** [comment]
Pues jose, entre ayer y hoy he cambiado muchísimas cosas.
Ahora mismo no puedo mezclar master. Lo haré esta noche si tengo tiempo

Ivan Ortega Alba

4º Grado en Ingeniería Informática
Especialidad en Tecnologías de la Comunicación
Escuela Técnica Superior de Ingeniería Informática y Telecomunicación.
Universidad de Granada

**Comment by joseluisfdezbueno** [comment]
Ok, tranquilo cuando puedas.
