### ISSUE TITLE
AJAX (Entrega 5)

### ISSUE THREAD

**Issue by ivanortegaalba** [CongressWebDevelopers/web-congreso#71]
- [X] Renovar Actividades por AJAX #68
- [x] Calcular importe por AJAX #69
- [x] Buscador en la lista de asistentes por AJAX #70

**Comment by ivanortegaalba** [comment]
@jota-ele256

**Comment by ivanortegaalba** [comment]
@jota-ele256 ya tengo todo hecho. Si me da tiempo hago algo con la API
